/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package perpustakaan;

import java.awt.Color;
import java.io.IOException;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableModel;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.ParseException;
import perpustakaan.utilities.ConvertDate;
import perpustakaan.utilities.konfigurasi;

/**
 *
 * @author Wildan
 */
public class ManagePeminjaman extends javax.swing.JFrame {

    /**
     * Creates new form ManagePeminjaman
     */
    
    private JSONArray listAnggota;
    private JSONArray listBukuSalinan;
    
    public ManagePeminjaman() {
        initComponents();
        setListAnggota();
        setListBukuSalinan();
        setTable();
        resetField();
        message.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        list_anggota = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        list_buku_salinan = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        return_at = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        button_create = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        message = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Management Peminjaman");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Management Peminjaman Buku");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Pilih Peminjam Buku");

        list_anggota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wildan Izhar Al Haqq", "Wldnz", " " }));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Pilih Buku");

        list_buku_salinan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buku A ", "BUKU C", " " }));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Pilih Tanggal Di Kembalikan");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama Lengkap", "Nama Buku", "Buku Panggilan", "Kondisi Buku", "Tanggal Dipinjam", "Tanggal Dibalikin", "Kondisi Dibalikan", "Status Peminjaman"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        button_create.setForeground(new java.awt.Color(51, 0, 51));
        button_create.setText("Buat Peminjaman");
        button_create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_createMousePressed(evt);
            }
        });

        jButton2.setText("Refresh Table");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        message.setText("message");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(button_create, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(message))
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(list_anggota, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(list_buku_salinan, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(return_at, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(831, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(message))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(list_anggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(list_buku_salinan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(return_at, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(button_create, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void button_createMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_createMousePressed
        try {
            JSONObject result = new konfigurasi().sendPostRequest("models/book/borrowed/add.php",getDataPeminjaman());
            if(result.get("isSuccess").equals(true)){
               setTable();
               message.setForeground(Color.GREEN);
               message.setText("Berhasil menambahkan Data Peminjaman Buku");
            }else{
               message.setForeground(Color.GREEN);
               message.setText((String)result.get("message"));
            }} catch (IOException | ParseException ex) {
            Logger.getLogger(ManagePeminjaman.class.getName()).log(Level.SEVERE, null, ex);
        }
        message.setVisible(true);
    }//GEN-LAST:event_button_createMousePressed

    
    private HashMap<String,String> getDataPeminjaman(){
        
        HashMap<String,String> peminjaman = new HashMap();
        for(int i=0; i <listAnggota.size(); i++){
           JSONObject data = (JSONObject) listAnggota.get(i);
           if(data.get("fullname") == list_anggota.getSelectedItem()){
               peminjaman.put("id_user",(String) data.get("id"));
           }
        }
        
        for(int i=0; i <listBukuSalinan.size(); i++){
           JSONObject data = (JSONObject) listBukuSalinan.get(i);
           if(data.get("call_number") == list_buku_salinan.getSelectedItem()){
               peminjaman.put("id_book_copy",(String) data.get("id"));
           }
        }
        
        peminjaman.put("return_at",ConvertDate.DateToEpochMililiseconds(return_at.getDate().toString()));
        peminjaman.put("borrowed_at",String.valueOf(new Date().getTime()));
        
        return peminjaman;
    }
    
    private void resetField(){
        list_anggota.setSelectedIndex(0);
        list_buku_salinan.setSelectedIndex(0);
        return_at.setDate(new Date());
    }
    
    private void setListAnggota(){
        list_anggota.removeAllItems();
       try {
            JSONObject result = new konfigurasi().sendGetRequest("models/anggota/all.php");
            if(result.get("isSuccess").equals(true)){
                JSONArray arr = (JSONArray) result.get("data");
                listAnggota = arr;
                if(!arr.isEmpty()){
                    for(int i=0; i <arr.size(); i++){
                        JSONObject data = (JSONObject) arr.get(i);
                        list_anggota.addItem((String) data.get("fullname"));
                    }
                }
            }
        } catch (IOException | ParseException ex) {
            Logger.getLogger(ManagePeminjaman.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void setListBukuSalinan(){
       list_buku_salinan.removeAllItems();
       try {
            JSONObject result = new konfigurasi().sendGetRequest("models/book/copy/all.php");
            if(result.get("isSuccess").equals(true)){
                JSONArray arr = (JSONArray) result.get("data");
                listBukuSalinan = arr;
                if(!arr.isEmpty()){
                    for(int i=0; i <arr.size(); i++){
                        JSONObject data = (JSONObject) arr.get(i);
                        list_buku_salinan.addItem((String) data.get("call_number"));
                    }
                }
            }
        } catch (IOException | ParseException ex) {
            Logger.getLogger(ManagePeminjaman.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void setTable(){
        try {
            TableModel tbl = table.getModel();
            JSONObject result = new konfigurasi().sendGetRequest("models/book/borrowed/all.php");
            if(result.get("isSuccess").equals(true)){
                JSONArray arr = (JSONArray) result.get("data");
                if(!arr.isEmpty()){
                    for(int i=0; i <arr.size(); i++){
                        JSONObject data = (JSONObject) arr.get(i);
                        tbl.setValueAt(data.get("fullname"),i, 0);
                        tbl.setValueAt(data.get("title"),i, 1);
                        tbl.setValueAt(data.get("call_number"),i, 2);
                        tbl.setValueAt(data.get("book_condition"),i, 3);
                        tbl.setValueAt(data.get("borrowed_at"),i, 4);
                        tbl.setValueAt(data.get("return_at"),i, 5);
                        tbl.setValueAt(data.get("return_condtion"),i, 6);
                        tbl.setValueAt(data.get("status"),i, 7);
                    }
                }
            }
        } catch (IOException | ParseException ex) {
            Logger.getLogger(ManagePeminjaman.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagePeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagePeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagePeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagePeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagePeminjaman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_create;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> list_anggota;
    private javax.swing.JComboBox<String> list_buku_salinan;
    private javax.swing.JLabel message;
    private com.toedter.calendar.JDateChooser return_at;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
