/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package perpustakaan;

import java.awt.Color;
import perpustakaan.utilities.DateToEpoch;
import java.io.IOException;
import java.time.LocalDate;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.ParseException;
import perpustakaan.utilities.konfigurasi;

/**
 *
 * @author Wildan
 */
public class ManagementBuku extends javax.swing.JFrame {

    
    private HashMap<String,String> clsn_arr;
    private String _clsn;
    private Boolean canContinue;
    private String id_buku;
    
    public ManagementBuku() {
        this.clsn_arr = new HashMap();
        initComponents();
        setClassificationNumber();
        clearAllFields();
        error_message.setVisible(false);
    }

/**
     * Creates new form ManagementBuku
     */
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        isbn_10 = new java.awt.TextField();
        jLabel3 = new javax.swing.JLabel();
        isbn_13 = new java.awt.TextField();
        title = new java.awt.TextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        author = new java.awt.TextField();
        publisher = new java.awt.TextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        publish_year = new com.toedter.calendar.JYearChooser();
        jLabel12 = new javax.swing.JLabel();
        category = new java.awt.TextField();
        jLabel13 = new javax.swing.JLabel();
        language = new com.toedter.components.JLocaleChooser();
        receiver_date = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        edition_number = new com.toedter.calendar.JYearChooser();
        total_pages = new com.toedter.calendar.JYearChooser();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        image_url = new java.awt.TextField();
        jLabel15 = new javax.swing.JLabel();
        status = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        classification_number = new javax.swing.JComboBox<>();
        button_create = new javax.swing.JButton();
        button_update = new javax.swing.JButton();
        button_delete = new javax.swing.JButton();
        button_clear = new javax.swing.JButton();
        error_message = new javax.swing.JLabel();
        cari_isbn10 = new javax.swing.JButton();
        cari_isbn13 = new javax.swing.JButton();
        cari_judul = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Management Buku");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Management Buku");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Kategori");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("ISBN 13");

        isbn_13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbn_13ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Judul");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("deskripsi");

        description.setColumns(20);
        description.setRows(5);
        jScrollPane1.setViewportView(description);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Penulis");

        author.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorActionPerformed(evt);
            }
        });

        publisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publisherActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Penerbit");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Tahun Terbit");

        publish_year.setValue(20);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("ISBN 10");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Bahasa");

        receiver_date.setDoubleBuffered(false);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Tanggal Diterima");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Edisi Ke");

        edition_number.setYear(1);

        total_pages.setYear(1);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Total Halaman");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("image-url");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("status");

        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "public", "private" }));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Nomor Klasifikasi");

        classification_number.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Karya Sastra", "Karya Sastra Inggris", " " }));

        button_create.setText("Buat Buku");
        button_create.setToolTipText("");
        button_create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                create_book(evt);
            }
        });

        button_update.setText("update buku");
        button_update.setToolTipText("");
        button_update.setEnabled(false);

        button_delete.setText("Delete Buku");
        button_delete.setToolTipText("");
        button_delete.setEnabled(false);
        button_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_deleteMousePressed(evt);
            }
        });

        button_clear.setText("Clear All");
        button_clear.setToolTipText("");
        button_clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_clearMousePressed(evt);
            }
        });

        error_message.setForeground(new java.awt.Color(255, 51, 51));
        error_message.setText("error_message");

        cari_isbn10.setText("Cari");
        cari_isbn10.setToolTipText("");
        cari_isbn10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cari_isbn10MousePressed(evt);
            }
        });

        cari_isbn13.setText("Cari");
        cari_isbn13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cari_isbn13MousePressed(evt);
            }
        });

        cari_judul.setText("Cari Judul");
        cari_judul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cari_judulMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel10)
                                                    .addComponent(jLabel8))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(publish_year, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(edition_number, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(total_pages, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(classification_number, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(218, 218, 218))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel12))
                                                .addGap(19, 19, 19)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(isbn_10, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(cari_isbn10))
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(isbn_13, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(cari_isbn13)))
                                                        .addGap(0, 0, Short.MAX_VALUE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(cari_judul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(author, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(publisher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                        .addGap(32, 32, 32)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(image_url, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel14)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(receiver_date, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addGap(18, 18, 18)
                                            .addComponent(language, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(11, 11, 11)
                                        .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(button_create, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(button_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(button_update, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                                    .addComponent(error_message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(language, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(receiver_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(image_url, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button_create, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(isbn_10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12))
                            .addComponent(cari_isbn10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(isbn_13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cari_isbn13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cari_judul, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(author, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(publisher, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(publish_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(edition_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(total_pages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(classification_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_update, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(error_message)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void isbn_13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbn_13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isbn_13ActionPerformed

    private void authorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_authorActionPerformed

    private void publisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publisherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_publisherActionPerformed

    private void create_book(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_book
        try {
            HashMap<String,String> book = getBookData();
            if(!canContinueToDoing(book))  {
                error_message.setForeground(Color.RED);
                error_message.setText("Pastikan Semua Kolom Terisi");
                error_message.setVisible(true);
                return;
            };
            konfigurasi konfigurasi = new konfigurasi();
            JSONObject result = konfigurasi.sendPostRequest("models/book/add.php", book);
            System.out.println(result.get("isSuccess").equals(true));
            if(result.get("isSuccess").equals(true)){
                this.clearAllFields();
                error_message.setForeground(Color.GREEN);
                error_message.setText("Berhasil membuat buku,");
                error_message.setVisible(true);
            }else{
                error_message.setForeground(Color.RED);
                error_message.setText(result.get("message").toString());
                error_message.setVisible(true);
            }
//       System.out.println(konfigurasi.convertToParams(book));
        } catch (IOException ex) {
            System.out.println("data yang diberikan null, pada IoExceptioon");
        } catch (ParseException ex) {
                        System.out.println("data yang diberikan null, pada ParseException");
//            Logger.getLogger(ManagementBuku.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_create_book

    private void button_clearMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_clearMousePressed
       this.clearAllFields();
    }//GEN-LAST:event_button_clearMousePressed

    private void cari_isbn10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cari_isbn10MousePressed
        try {
            String isbn10 = isbn_10.getText();
            if(isbn10.isEmpty()) return;
            JSONObject result = new konfigurasi().sendGetRequest("models/book/cari.php?isbn_10="+isbn10);
            if(result.get("isSuccess").equals(true) && result.get("isFound").equals(true)){
                JSONArray arr = (JSONArray) result.get("data");
                 if(!arr.isEmpty()){
                    JSONObject book = (JSONObject) arr.get(0);
                    this.setField(book);
                    error_message.setForeground(Color.GREEN);
                    error_message.setText("Berhasil mencari isbn_10");
                    error_message.setVisible(true);
                    return;
                }
            } 
            error_message.setForeground(Color.RED);
            error_message.setText(result.get("message").toString());
            error_message.setVisible(true);
        } catch (IOException | ParseException ex) {
            Logger.getLogger(ManagementBuku.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cari_isbn10MousePressed

    private void cari_isbn13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cari_isbn13MousePressed
        try {
            String isbn13 = isbn_13.getText();
            if(isbn13.isEmpty()) return;
            JSONObject result = new konfigurasi().sendGetRequest("models/book/cari.php?isbn_13="+isbn13);
            if(result.get("isSuccess").equals(true) && result.get("isFound").equals(true)){
                JSONArray arr = (JSONArray) result.get("data");
               if(!arr.isEmpty()){
                    JSONObject book = (JSONObject) arr.get(0);
                    this.setField(book);
                    error_message.setForeground(Color.GREEN);
                    error_message.setText("Berhasil mencari isbn_13");
                    error_message.setVisible(true);
                    return;
                }
                
            }
            error_message.setForeground(Color.RED);
            error_message.setText(result.get("message").toString());
            error_message.setVisible(true);
        } catch (IOException | ParseException ex) {
            Logger.getLogger(ManagementBuku.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cari_isbn13MousePressed

    private void cari_judulMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cari_judulMousePressed
        try {
            String judul = title.getText();
            if(judul.isEmpty()) return;
            JSONObject result = new konfigurasi().sendGetRequest("models/book/cari.php?title="+judul);
            if(result.get("isSuccess").equals(true) && result.get("isFound").equals(true)){
                JSONArray arr = (JSONArray) result.get("data");
                if(!arr.isEmpty()){
                    JSONObject book = (JSONObject) arr.get(0);
                    this.setField(book);
                    error_message.setForeground(Color.GREEN);
                    error_message.setText("Berhasil mencari judul buku");
                    error_message.setVisible(true);
                    return;
                }
            }
           error_message.setForeground(Color.RED);
            error_message.setText(result.get("message").toString());
            error_message.setVisible(true);
        } catch (IOException | ParseException ex) {
            Logger.getLogger(ManagementBuku.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cari_judulMousePressed

    private void button_deleteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_deleteMousePressed
      
        try {
            System.out.println("delete book dengan id =" +id_buku);
            HashMap<String,String> book = new HashMap();
            book.put("id", id_buku);
            JSONObject result = new konfigurasi().sendPostRequest("models/book/delete.php",book);
            if(result.get("isSuccess").equals(true)){
                error_message.setForeground(Color.ORANGE);
                error_message.setText(result.get("message").toString());
                error_message.setVisible(true);
                this.clearAllFields();
                return;
            }
            error_message.setForeground(Color.RED);
            error_message.setText(result.get("message").toString());
            error_message.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(ManagementBuku.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(ManagementBuku.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_button_deleteMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagementBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagementBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagementBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagementBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagementBuku().setVisible(true);
            }
        });
    }
    
    
    private void setClassificationNumber(){
        try {
            classification_number.removeAllItems();
            JSONObject obj = new konfigurasi().sendGetRequest("models/Classification-Numbers.php");
            JSONArray arr = (JSONArray) obj.get("data");
            for(int i =0; i < arr.size();i++ ){
                JSONObject clsn = (JSONObject) arr.get(i);
                classification_number.addItem(clsn.get("classification").toString());
                clsn_arr.put(clsn.get("classification").toString(),clsn.get("id").toString());
            }
        } catch (IOException ex) {
            Logger.getLogger(ManagementBuku.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(ManagementBuku.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void clearAllFields(){
        id_buku = "";
        isbn_10.setText("");
        isbn_13.setText("");
        title.setText("");
        description.setText("");
        author.setText("");
        publisher.setText("");
        publish_year.setValue(1);
        edition_number.setValue(1);
        total_pages.setValue(1);
        classification_number.setSelectedIndex(1);
        category.setText("");
        language.setSelectedIndex(0);
        image_url.setText("https://cdn2.hubspot.net/hubfs/242200/shutterstock_774749455.jpg");
        status.setSelectedIndex(0);
        button_delete.setEnabled(false);
    }
    
    private HashMap<String,String>  getBookData(){
    HashMap<String,String> book = new HashMap();
        book.put("isbn_10", isbn_10.getText());
        book.put("isbn_13", isbn_13.getText());
        book.put("title", title.getText());
        book.put("author", author.getText());
        book.put("description", description.getText());
        book.put("publisher", publisher.getText());
        book.put("publish_year", String.valueOf(publish_year.getValue()));
        book.put("edition_number", String.valueOf(edition_number.getValue()));
        book.put("total_pages", String.valueOf(total_pages.getValue()));
        book.put("classification-number",this.getClassificationNumber()); // If you add this field
        book.put("category", category.getText());
        book.put("language", language.getSelectedItem().toString());
        book.put("receiver-date", DateToEpoch.DateToEpochMililiseconds(receiver_date.getDate().toString()));
        book.put("image-url", image_url.getText());
        book.put("status", status.getSelectedItem().toString());
        return book;
    }
    
    private String getClassificationNumber(){
        String clsn = classification_number.getSelectedItem().toString();
        clsn_arr.forEach((k, v) -> {
            if(k.equals(clsn)){   
               _clsn = v;
            }
        });
        return _clsn;
    }
    
     private String getClassificationByNumber(String number){
        clsn_arr.forEach((k, v) -> {
            if(v.equals(number)){   
                System.out.println(k);
               _clsn = k;
            }
        });
        return _clsn;
    }
    
    private Boolean canContinueToDoing(HashMap<String,String> data){
        canContinue = true;
        data.forEach((k, v) -> {
            if(v.isEmpty() && !k.contains("isbn")){
                if(k.equals("image_url")){
                    image_url.setText("https://cdn2.hubspot.net/hubfs/242200/shutterstock_774749455.jpg");
                }else{
                    canContinue = false;
                }
            }
        });
        return canContinue;
    }
    
    private void setField(JSONObject book){
        id_buku = (String) book.get("id");
        isbn_10.setText((String) book.get("isbn_10"));
        isbn_13.setText((String) book.get("isbn_13"));
        title.setText(book.get("title").toString());
        description.setText(book.get("description").toString());
        author.setText(book.get("author").toString());
        publisher.setText(book.get("publisher").toString());
        publish_year.setValue(Integer.parseInt((String) book.get("publication_year")));
        edition_number.setValue(Integer.parseInt((String) book.get("edition_number")));
        total_pages.setValue(Integer.parseInt((String) book.get("total_pages")));
        classification_number.setSelectedItem(this.getClassificationByNumber((String) book.get("clsn_id")));
        category.setText(book.get("category").toString());
        language.setSelectedItem(book.get("language").toString());
        image_url.setText(book.get("image_url").toString());
        status.setSelectedItem(book.get("status").toString());
        button_delete.setEnabled(true);
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField author;
    private javax.swing.JButton button_clear;
    private javax.swing.JButton button_create;
    private javax.swing.JButton button_delete;
    private javax.swing.JButton button_update;
    private javax.swing.JButton cari_isbn10;
    private javax.swing.JButton cari_isbn13;
    private javax.swing.JButton cari_judul;
    private java.awt.TextField category;
    private javax.swing.JComboBox<String> classification_number;
    private javax.swing.JTextArea description;
    private com.toedter.calendar.JYearChooser edition_number;
    private javax.swing.JLabel error_message;
    private java.awt.TextField image_url;
    private java.awt.TextField isbn_10;
    private java.awt.TextField isbn_13;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private com.toedter.components.JLocaleChooser language;
    private com.toedter.calendar.JYearChooser publish_year;
    private java.awt.TextField publisher;
    private com.toedter.calendar.JDateChooser receiver_date;
    private javax.swing.JComboBox<String> status;
    private java.awt.TextField title;
    private com.toedter.calendar.JYearChooser total_pages;
    // End of variables declaration//GEN-END:variables
}